name: Nightly Regression

on:
  schedule:
    - cron: "0 2 * * *"     # 02:00 UTC every night
  workflow_dispatch:          # allow manual trigger
    inputs:
      environment:
        description: "Target environment"
        required: false
        default: "staging"
        type: choice
        options: [staging, production]
      browser:
        description: "Browser(s) to test"
        required: false
        default: "all"
        type: choice
        options: [all, chromium, firefox, webkit]
      test_markers:
        description: "Pytest markers to run (leave empty for full suite)"
        required: false
        default: ""

jobs:
  # ── Full regression across browsers ───────────────────────────────────────
  regression:
    name: Regression — ${{ matrix.browser }}
    runs-on: ubuntu-latest
    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        browser: ${{ fromJSON(inputs.browser == 'all' || inputs.browser == '' && 'true' && '["chromium","firefox","webkit"]' || format('["{0}"]', inputs.browser)) }}
        # Shorthand: always run all 3 browsers on schedule; respect input on manual runs
        include:
          - browser: chromium
          - browser: firefox
          - browser: webkit

    env:
      TEST_ENV: ${{ inputs.environment || 'staging' }}
      BASE_URL: ${{ secrets.STAGING_BASE_URL }}
      API_BASE_URL: ${{ secrets.STAGING_API_BASE_URL }}
      TEST_USERNAME: ${{ secrets.STAGING_TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.STAGING_TEST_PASSWORD }}
      API_TOKEN: ${{ secrets.STAGING_API_TOKEN }}
      HEADLESS: "true"
      BROWSER: ${{ matrix.browser }}
      SCREENSHOT_ON_FAILURE: "true"
      TRACE_ON_FAILURE: "true"
      VIDEO_ON_FAILURE: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Install Playwright — ${{ matrix.browser }}
        run: playwright install ${{ matrix.browser }} --with-deps

      - name: Run regression suite
        run: |
          MARKERS="${{ inputs.test_markers }}"
          MARKER_FLAG=${MARKERS:+"-m \"${MARKERS}\""}

          pytest ${MARKER_FLAG} \
            -n auto \
            --timeout=120 \
            --tb=short \
            --junitxml=reports/junit-${{ matrix.browser }}.xml \
            --alluredir=reports/allure-results \
            --cov=utils \
            --cov=config \
            --cov-report=xml:reports/coverage.xml \
            --cov-report=html:reports/coverage-html

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: reports/junit-${{ matrix.browser }}.xml

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-${{ matrix.browser }}-${{ github.run_number }}
          path: reports/allure-results
          retention-days: 30

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failures-${{ matrix.browser }}-${{ github.run_number }}
          path: |
            reports/screenshots/
            reports/traces/
            reports/videos/
          retention-days: 14

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-${{ matrix.browser }}-${{ github.run_number }}
          path: reports/coverage-html
          retention-days: 30

  # ── Allure report publish (aggregates all browsers) ───────────────────────
  publish-allure-report:
    name: Publish Allure Report
    runs-on: ubuntu-latest
    needs: regression
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Download all Allure results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-*-${{ github.run_number }}
          merge-multiple: true
          path: reports/allure-results

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: reports/allure-results
          allure_report: reports/allure-report
          allure_history: allure-history
          keep_reports: 30

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports/allure-report

  # ── Notify ────────────────────────────────────────────────────────────────
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: regression
    if: always()
    steps:
      - name: Compute status
        id: status
        run: |
          if [ "${{ needs.regression.result }}" = "success" ]; then
            echo "icon=✅" >> $GITHUB_OUTPUT
            echo "color=good" >> $GITHUB_OUTPUT
          else
            echo "icon=❌" >> $GITHUB_OUTPUT
            echo "color=danger" >> $GITHUB_OUTPUT
          fi

      - name: Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "attachments": [{
                "color": "${{ steps.status.outputs.color }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${{ steps.status.outputs.icon }} *Nightly Regression* — `${{ github.repository }}`\n*Result:* ${{ needs.regression.result }}\n*Environment:* ${{ inputs.environment || 'staging' }}\n*<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>* | *<https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}|Allure Report>*"
                    }
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
