name: PR Gate

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ── 1. Code Quality (fast — runs in parallel with tests) ──────────────────
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dev dependencies
        run: pip install -e ".[dev]"

      - name: Ruff lint
        run: ruff check .

      - name: Black format check
        run: black --check .

      - name: Mypy type check
        run: mypy .

  # ── 2. Smoke + P0 Tests ───────────────────────────────────────────────────
  test-pr:
    name: Smoke & P0 Tests (${{ matrix.test-type }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: lint              # only run if linting passes

    strategy:
      fail-fast: false       # don't cancel other matrix legs on failure
      matrix:
        test-type: [api, ui]

    env:
      TEST_ENV: staging
      BASE_URL: ${{ secrets.STAGING_BASE_URL }}
      API_BASE_URL: ${{ secrets.STAGING_API_BASE_URL }}
      TEST_USERNAME: ${{ secrets.STAGING_TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.STAGING_TEST_PASSWORD }}
      API_TOKEN: ${{ secrets.STAGING_API_TOKEN }}
      HEADLESS: "true"
      SCREENSHOT_ON_FAILURE: "true"
      TRACE_ON_FAILURE: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Install Playwright browsers
        if: matrix.test-type == 'ui'
        run: playwright install chromium --with-deps

      - name: Run smoke & P0 tests — ${{ matrix.test-type }}
        run: |
          pytest -m "( smoke or p0 ) and ${{ matrix.test-type }}" \
            -n auto \
            --timeout=60 \
            --tb=short \
            --junitxml=reports/junit-${{ matrix.test-type }}.xml \
            --alluredir=reports/allure-results \
            --cov=utils \
            --cov=config \
            --cov-report=xml:reports/coverage-${{ matrix.test-type }}.xml

      # Publish JUnit results as PR check annotations
      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: reports/junit-*.xml
          comment_mode: off            # keep PR comments clean; annotations only

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-pr-${{ matrix.test-type }}-${{ github.run_number }}
          path: reports/allure-results
          retention-days: 7

      - name: Upload screenshots & traces on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-artifacts-${{ matrix.test-type }}-${{ github.run_number }}
          path: |
            reports/screenshots/
            reports/traces/
          retention-days: 7

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.test-type }}-${{ github.run_number }}
          path: reports/coverage-${{ matrix.test-type }}.xml
          retention-days: 7

  # ── 3. Coverage Gate ──────────────────────────────────────────────────────
  coverage-gate:
    name: Coverage Gate
    runs-on: ubuntu-latest
    needs: test-pr
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*-${{ github.run_number }}
          merge-multiple: true
          path: reports/

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install coverage
        run: pip install coverage

      - name: Combine & enforce 80% minimum
        run: |
          coverage combine reports/coverage-*.xml || true
          coverage report --fail-under=80
